name: recipe_book_app
description: "A Flutter Recipe Book App for CW-02."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Agelia
      fonts:
        - asset: assets/fonts/agelia.otf
        